other_params:
- float_params:
    rates: [1.5, 0.2, 0.6, 1.0, 3.0]
  int_params: {}
- float_params: {}
  int_params:
    rate_process_partition_index: [0]
init_state_values:
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
init_time_value: 1.0
seeds: [563, 8312]
state_widths: [5, 5]
state_history_depths: [2, 2]
timesteps_history_depth: 2